version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017/RIT"  # Update MongoDB URI
      JWT_SECRET: "CLUBHANDLINGPROJECT"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
